### ISSUE TITLE
no module names osr

### ISSUE THREAD

**Issue by ecodiv** [romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA#10]
When loading the plugin on QGIS 3.16.2 on Ubuntu 20.04, I am getting the following error message:

```
Couldn't load plugin 'multi_criteria' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'osr' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/multi_criteria/__init__.py", line 35, in classFactory
    from .multi_criteria import MultiCriteria
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/multi_criteria/multi_criteria.py", line 39, in 
    import osr
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osr'
```

**Comment by felxcon** [comment]
Dear romariocarvalhoneto,
I am looking forward to use your plugin WMCA:). However, it appears that there might be compatibility problems with QGIS v3.20 onwards (Win10). I get the following >ModuleNotFoundError: No module named 'osr'< when trying to install WMCA. I tried several older versions of QGIS for installing the plugin and found no errors for QGIS versions 3.4.15 til 3.18.3 (=it works in QGIS v3.4.15 to v3.18.3). I found this issue not only arises for your Plugin WMCA but also RasterMCDA (https://github.com/awallner-WallE/RasterMCDA-QGIS_Plugin).

**Comment by biglimp** [comment]
There is an easy fix to this. osr is now found within the osgeo package so just change line 39 in **multi_criteria.py** to:
`from osgeo import osr`

**Comment by bellanz80** [comment]
Genial! 
Thank you! I haven't been able to use the plug for a month, always because of the OSR error.
Now, just with the change of from osgeo import osr, it works perfectly in QGIS 3.26!
Thank you!

**Comment by romariocarvalhoneto** [comment]
Thank you all for the contribution. I will fix it.

**Comment by romariocarvalhoneto** [comment]
Fixed. Already available in the QGIS repository as well. Thank you all once again.
