### ISSUE TITLE
Error number of Clases

### ISSUE THREAD

**Issue by bellanz80** [romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA#2]
Hi. 
I have 6 rasters, all aligned, with the same pixel size and vertical and horizontal pixel number.
All classified in the same way, from 1 to 5.
But, one of these rasters, when loading, is marked as containing more than 100 classes ... and does not allow using it.
What could it be?
Thank you so much!

![image](https://user-images.githubusercontent.com/38449926/83181959-3975c680-a0eb-11ea-880f-2edbc947a086.png)

annex the raster
[nd_RECLAS_CUERPOS_AGUA_OK.zip](https://github.com/romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA/files/4697640/nd_RECLAS_CUERPOS_AGUA_OK.zip)

**Comment by ambarja** [comment]
Hello @bellanz80 I've had the same problem and just I went back reclassify of raster in a table of 5x3 and It was resulted. 
![](https://github.com/barja8/Friends/blob/master/QGIS/Img/Multicriterie/img01.png?raw=true)
![](https://github.com/barja8/Friends/blob/master/QGIS/Img/Multicriterie/img02.png?raw=true)
![](https://github.com/barja8/Friends/blob/master/QGIS/Img/Multicriterie/img03.png?raw=true)

**Comment by romariocarvalhoneto** [comment]
@bellanz80 , if you use a raster with too many classes, the process of giving grades for each class on the next page will be very "heavy" I would say, since you will have to do it manually, one by one. This is not normally done on these kind of analysis. You have to group classes according to what @barja8 did and is orientated by the message from the plugin, that is, to use the "Reclassify by Table" tool.

**Comment by bellanz80** [comment]
I very much appreciate the support on the github of the QGIS WMCA plug.
But, I still have the same error. The raster I shared with you, I classified it again, but it keeps giving me the same error.
May I ask you which process did you use? I use the GDAL RECLASS
Video annex.
Ciao and thanks!

QGIS 3.12.3
windows 10 64 bit.
New profile only 1 plugin

[2020-05-29_09h39_44.zip](https://github.com/romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA/files/4702551/2020-05-29_09h39_44.zip)

**Comment by bellanz80** [comment]
> @bellanz80 , if you use a raster with too many classes, the process of giving grades for each class on the next page will be very "heavy" I would say, since you will have to do it manually, one by one. This is not normally done on these kind of analysis. You have to group classes according to what @barja8 did and is orientated by the message from the plugin, that is, to use the "Reclassify by Table" tool.

Thank you very much Romario. That data had been taken into account from the beginning, in fact the raster I shared before, is already classified into 5 classes. So I can't understand the mistake. I did a new classification, as suggested by Borja, but I have the same error.
I used the same classification process for 6 rasters, and only one is the one that gives me class error ...
Thanks for the support!

Luca

**Comment by romariocarvalhoneto** [comment]
@bellanz80 your raster have more than 100 values in it, as you can see on the screen I sent. The values are (at least those that I found) between the 1 and the 2. You still have to reclassify you raster to enter it into your analysis. 

![erroRasterGitHub](https://user-images.githubusercontent.com/52353524/83276741-756e6180-a1a7-11ea-8f78-787d7a1fa90b.jpg)

**Comment by romariocarvalhoneto** [comment]
> I very much appreciate the support on the github of the QGIS WMCA plug.
> But, I still have the same error. The raster I shared with you, I classified it again, but it keeps giving me the same error.
> May I ask you which process did you use? I use the GDAL RECLASS
> Video annex.
> Ciao and thanks!
> 
> QGIS 3.12.3
> windows 10 64 bit.
> New profile only 1 plugin
> 
> [2020-05-29_09h39_44.zip](https://github.com/romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA/files/4702551/2020-05-29_09h39_44.zip)

You are using the right tool but you have to reclassify by table like this:
0 to 1 -> 1
1 to 2 -> 2
2 to 3 -> 3
3 to 4 -> 4
4 to 5 -> 4

I will show the results in the screens:

![deuCerto](https://user-images.githubusercontent.com/52353524/83279011-d51a3c00-a1aa-11ea-8084-f95b751f89f1.jpg)

![deucert3Tabela](https://user-images.githubusercontent.com/52353524/83279431-786b5100-a1ab-11ea-8bee-8959b22855cf.jpg)

![deucerto2](https://user-images.githubusercontent.com/52353524/83279449-7ef9c880-a1ab-11ea-90f0-0e9a57e64e2e.jpg)

**Comment by bellanz80** [comment]
Very Thnak's. I review my total flow work.
