### ISSUE TITLE
Error to install from .ZIP

### ISSUE THREAD

**Issue by bellanz80** [romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA#3]
Hi. 
I am trying to solve the ISSUE on the number of classes. I opened a new profile, and tried to install the plug from .zip, cloned from GitHub.
But some error messages appear.
QGIS 3.12.3
Windows 10 64 bit

Luca

![image](https://user-images.githubusercontent.com/38449926/83277213-58ca2d80-a197-11ea-9c71-6d9f80dadc9a.png)

Ocurrió un error durante la ejecución del siguiente código:
pyplugin_installer.instance().installFromZipFile(r'C:\Users\UV\Downloads\Weighted-Multi-Criteria-Analysis---WMCA-master.zip')

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'Weighted-Multi-Criteria-Analysis---WMCA-master' has no attribute 'classFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\pyplugin_installer\installer.py", line 636, in installFromZipFile
    if startPlugin(pluginName):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 354, in startPlugin
    if not _startPlugin(packageName):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 336, in _startPlugin
    _unloadPluginModules(packageName)
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 448, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'Weighted-Multi-Criteria-Analysis---WMCA-master'

Versión de Python:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

Versión de QGIS:
3.12.3-București 'București', 8234261527

Ruta de Python:
['C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python', 'C:/Users/UV/AppData/Roaming/QGIS/QGIS3\\profiles\\pulito/python', 'C:/Users/UV/AppData/Roaming/QGIS/QGIS3\\profiles\\pulito/python/plugins', 'C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37\\Scripts', 'C:\\Program Files\\QGIS 3.12\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.12\\bin', 'C:\\Users\\UV\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.12\\apps\\Python37\\lib\\site-packages\\Pythonwin', 'C:/Users/UV/AppData/Roaming/QGIS/QGIS3\\profiles\\pulito/python']

**Comment by romariocarvalhoneto** [comment]
> Hi.
> I am trying to solve the ISSUE on the number of classes...

I answered this one on the last Issue. 

https://github.com/romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA/issues/2#issuecomment-636049081

I haven't tried to install it from .zip, but should work, because it is a copy of the one at the QGIS repository. Please let me know if you still having any issue on stalling it by .zip

**Comment by romariocarvalhoneto** [comment]
I just tried to install it by zip. The thing is that when you download it, the folder comes inside of another zip. I may change that in the future, but for now you you can unzip the folder that you download and zip the one inside. The QGIS will recognize it. Or just download from the QGIS repository.
